### ISSUE TITLE
flask-introduction repo

### ISSUE THREAD

**Issue by toddfh** [rmotr-curriculum/flask-tutorial-step-by-step-questions#1]
I can't seem to find the Flask introduction repository on github....the one Santiago is using in the vids.  ??

**Assignment**: http://learn.rmotr.com/python/flask-tutorial-step-by-step/first-steps/our-first-webapp

**Comment by santiagobasulto** [comment]
Here it goes 😁 https://github.com/rmotr/flask-introduction

**Comment by kvnloughead** [comment]
I had to type in the url for the repo manually from the video.  A link on the main page for the video would be great.
