### ISSUE TITLE
Insufficient instruction

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/flask-tutorial-step-by-step-questions#3]
I felt that the material covered in this video in no way prepared us for the project following this video 'Your first Flask app'.  A lot of it could be figured out by looking at the test but the one with the query parameter... I ended up looking at the solution and it seemed completely out of the blue.

**Assignment**: http://learn.rmotr.com/python/flask-tutorial-step-by-step/first-steps/our-first-webapp

**Comment by santiagobasulto** [comment]
Thanks for the feedback @jjk235! I'll look it up and add some comments. But it's perfectly fine to look up things and figure them out by yourself, it's a great achievement! That's how full time developers work, googling everything all the time 😛
