### ISSUE TITLE
Please add the link to your repo to this lesson page

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/flask-tutorial-step-by-step-questions#4]
thanks

**Assignment**: http://learn.rmotr.com/python/flask-tutorial-step-by-step/first-steps/application-setup

**Comment by bbookman** [comment]
oops, never mind.  i see i can click the github icon

**Comment by kvnloughead** [comment]
I don't see any github icon linking to the repo.  Am I missing it somehow?
